id: BTb6THcdxUKTvfyVc8h1Gw
projectId: LwlbST-qsUqes7ejMO9bEw
projectName: My first Project
created: 2022-02-21T07:12:33.5980772Z
owner: Anushka V
protocol: 1
tests:
- id: wVQM8-4c6keBanePTV3i8Q
  name: Accelerate Digital
  description: Accelerate Digital Assessment
  platform: Web
  type: Web
  driverType: Chrome
  version: 0.1
  creationDate: 2022-02-19T16:47:47.0000000
  modificationDate: 2022-02-19T20:01:18.0000000
  settings:
    automationAssistant: true
    appId: wbJD6j1AGUyd5gGVjEDVww
    stepSleepTime: 500
    stepTimeout: 15000
    stepSleepTiming: Before
    stepFailureBehaviorType: Abort
    stepTakeScreenshotConditionType: Failure
  application:
    id: wbJD6j1AGUyd5gGVjEDVww
    name: TestProject Example
    description: TestProject example web application
    url: https://example.testproject.io/web/
    platform: Web
  steps:
  - id: jTWs8ZETvUGo8KPSJ0gkBw
    comments: ''
    enabled: true
    invertResult: false
    order: 1
    repeat: 1
    type: Action
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 49c5d8d8-4ba8-42f0-823d-702e6acfb23a
      source: System
    parameterMaps:
    - name: url
      value: https://accounts.google.com/signin/v2/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&service=mail&sacu=1&rip=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: FY-suaBL8k-OpLmVM8r9XA
    comments: ''
    enabled: true
    invertResult: false
    order: 2
    repeat: 1
    type: Action
    elementId: u_CMYg688EK8O0LJBPmMSA
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 6f94fdaa-0041-4265-b73b-ecfcbe702d66
      source: System
    parameterMaps:
    - name: keys
      value: '{{mailid}}'
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: xlyTeuttmUaBaOc6ihR4Yg
    comments: ''
    enabled: true
    invertResult: false
    order: 3
    repeat: 1
    type: Action
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 928bf14e-7a56-4371-b92a-9cb9de53f632
      source: System
    parameterMaps:
    - name: keys
      value: TAB
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: mI7AhlFZmk2-gF-PqzZlog
    comments: ''
    enabled: true
    invertResult: false
    order: 4
    repeat: 1
    type: Action
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 928bf14e-7a56-4371-b92a-9cb9de53f632
      source: System
    parameterMaps:
    - name: keys
      value: TAB
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: _JmpTi_jWU-kdWFAtp1wQw
    comments: ''
    enabled: true
    invertResult: false
    order: 5
    repeat: 1
    type: Action
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 928bf14e-7a56-4371-b92a-9cb9de53f632
      source: System
    parameterMaps:
    - name: keys
      value: TAB
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: DkA5hAuGwUW6j6vQB6cW5w
    comments: ''
    enabled: true
    invertResult: false
    order: 6
    repeat: 1
    type: Action
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 928bf14e-7a56-4371-b92a-9cb9de53f632
      source: System
    parameterMaps:
    - name: keys
      value: ENTER
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: aoZqb6VFPU-mHnC-bLRpQQ
    comments: ''
    enabled: true
    invertResult: false
    order: 7
    repeat: 1
    type: Action
    elementId: MGd-TUziQEKKA_xHc1tlHA
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 6f94fdaa-0041-4265-b73b-ecfcbe702d66
      source: System
    parameterMaps:
    - name: keys
      value: '{{pwd}}'
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: c7ptNzoY8kihSzJBHMF5kw
    comments: ''
    enabled: true
    invertResult: false
    order: 8
    repeat: 1
    type: Action
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 928bf14e-7a56-4371-b92a-9cb9de53f632
      source: System
    parameterMaps:
    - name: keys
      value: TAB
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: SGCyRdtOTEemASCC0xCDdw
    comments: ''
    enabled: true
    invertResult: false
    order: 9
    repeat: 1
    type: Action
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 928bf14e-7a56-4371-b92a-9cb9de53f632
      source: System
    parameterMaps:
    - name: keys
      value: TAB
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: gKQw-IPT40aEqSVjiOk2sQ
    comments: ''
    enabled: true
    invertResult: false
    order: 10
    repeat: 1
    type: Action
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 928bf14e-7a56-4371-b92a-9cb9de53f632
      source: System
    parameterMaps:
    - name: keys
      value: ENTER
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: caRfbGgdckW-wsGvIadQ7Q
    comments: ''
    enabled: true
    invertResult: false
    order: 11
    repeat: 1
    type: Action
    elementId: MGd-TUziQEKKA_xHc1tlHA
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 6f94fdaa-0041-4265-b73b-ecfcbe702d66
      source: System
    parameterMaps:
    - name: keys
      value: '{{pwd}}'
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: 3Ake0D7MCUqlLzQfX9m9Ng
    comments: ''
    enabled: true
    invertResult: false
    order: 12
    repeat: 1
    type: Action
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 928bf14e-7a56-4371-b92a-9cb9de53f632
      source: System
    parameterMaps:
    - name: keys
      value: TAB
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: v_i9rg90oU-2Bt9VAuJ6Xg
    comments: ''
    enabled: true
    invertResult: false
    order: 13
    repeat: 1
    type: Action
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 928bf14e-7a56-4371-b92a-9cb9de53f632
      source: System
    parameterMaps:
    - name: keys
      value: TAB
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: KRVg3ImFkkuklBEo2ARVmQ
    comments: ''
    enabled: true
    invertResult: false
    order: 14
    repeat: 1
    type: Action
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 928bf14e-7a56-4371-b92a-9cb9de53f632
      source: System
    parameterMaps:
    - name: keys
      value: ENTER
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: ArLivh26CE-nAb0iAWuYNQ
    comments: ''
    enabled: true
    invertResult: false
    order: 15
    repeat: 1
    type: Action
    elementId: MGd-TUziQEKKA_xHc1tlHA
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 85da72d0-c5a4-4587-be33-8cb3b5fa7910
      source: System
    parameterMaps:
    - name: text
      value: ''
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: ptwAt4CrZUKdeeoXXWI_7A
    comments: ''
    enabled: true
    invertResult: true
    order: 16
    repeat: 1
    type: Action
    elementId: Wuaqwk6ys06ENNjaUBuyuw
    settings:
      sleepTime: -1
      timeout: 12898
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 02d572b2-d610-4700-9ad3-40076ddb9807
      source: System
    parameterMaps: []
    conditions: []
    validations: []
    contexts: []
  - id: fMggfzQPt0aS3uVdKxSsRg
    comments: ''
    enabled: false
    invertResult: false
    order: 17
    repeat: 1
    type: Action
    settings:
      sleepTime: -1
      timeout: 21009
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 928bf14e-7a56-4371-b92a-9cb9de53f632
      source: System
    parameterMaps:
    - name: keys
      value: TAB
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: Rtjgy40jzEq9bWNsDEmGrw
    comments: ''
    enabled: true
    invertResult: false
    order: 18
    repeat: 18
    type: Action
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 928bf14e-7a56-4371-b92a-9cb9de53f632
      source: System
    parameterMaps:
    - name: keys
      value: TAB
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: wDnbEzNMiU6Q9v2JXlthCA
    comments: ''
    enabled: true
    invertResult: false
    order: 19
    repeat: 2
    type: Action
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 928bf14e-7a56-4371-b92a-9cb9de53f632
      source: System
    parameterMaps:
    - name: keys
      value: ENTER
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: uL2CD20vk0idOTRnQ9GVhw
    comments: ''
    enabled: true
    invertResult: false
    order: 20
    repeat: 1
    type: Action
    elementId: u_CMYg688EK8O0LJBPmMSA
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 6f94fdaa-0041-4265-b73b-ecfcbe702d66
      source: System
    parameterMaps:
    - name: keys
      value: '{{mailid}}'
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: ESuA6nrqkE6isA0bmfNNTg
    comments: ''
    enabled: true
    invertResult: false
    order: 21
    repeat: 1
    type: Action
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 928bf14e-7a56-4371-b92a-9cb9de53f632
      source: System
    parameterMaps:
    - name: keys
      value: TAB
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: fO94DWteVUuJUSSiOqLvmA
    comments: ''
    enabled: true
    invertResult: false
    order: 22
    repeat: 1
    type: Action
    elementId: u_CMYg688EK8O0LJBPmMSA
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 6f94fdaa-0041-4265-b73b-ecfcbe702d66
      source: System
    parameterMaps:
    - name: keys
      value: '{{sub}}'
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: c3h4PLwCn0GTNMdytC1P8A
    comments: ''
    enabled: true
    invertResult: false
    order: 23
    repeat: 1
    type: Action
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 928bf14e-7a56-4371-b92a-9cb9de53f632
      source: System
    parameterMaps:
    - name: keys
      value: TAB
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: fa0Qg_NHL024F6Mq5OiDIg
    comments: ''
    enabled: true
    invertResult: false
    order: 24
    repeat: 1
    type: Action
    elementId: u_CMYg688EK8O0LJBPmMSA
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 6f94fdaa-0041-4265-b73b-ecfcbe702d66
      source: System
    parameterMaps:
    - name: keys
      value: '{{msg}}'
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: qx3KUDpiiE2chzw9XJ6mqQ
    comments: ''
    enabled: true
    invertResult: false
    order: 25
    repeat: 1
    type: Action
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 928bf14e-7a56-4371-b92a-9cb9de53f632
      source: System
    parameterMaps:
    - name: keys
      value: TAB
      direction: Input
    conditions: []
    validations: []
    contexts: []
  - id: GmFeNVB27UKX6aEp7NNP0g
    comments: ''
    enabled: true
    invertResult: false
    order: 26
    repeat: 1
    type: Action
    settings:
      sleepTime: -1
      timeout: -1
      sleepTiming: Inherit
      failureBehaviorType: Inherit
      takeScreenshotConditionType: Inherit
    action:
      id: 928bf14e-7a56-4371-b92a-9cb9de53f632
      source: System
    parameterMaps:
    - name: keys
      value: ENTER
      direction: Input
    conditions: []
    validations: []
    contexts: []
  parameters:
  - name: pwd
    description: password for mail id
    type: Input
  - name: mailid
    description: ''
    type: Input
  - name: sub
    description: ''
    value: Demo Subjecr
    type: Input
  - name: msg
    description: ''
    value: This is a demo message please ignore
    type: Input
auxTests: []
elements:
- id: Wuaqwk6ys06ENNjaUBuyuw
  name: Address
  description: Address input
  type:
    id: jUwODgyNjAyNzk2NTk1NDY
    name: Textbox
    source: System
  locators:
  - name: ID
    value: address
    priority: 0
- id: u_CMYg688EK8O0LJBPmMSA
  name: email1
  description: selects email
  type:
    id: jUwODgyNjAyNzk2NTk1ODI
    name: blink
    source: System
  locators:
  - name: TAGNAME
    value: input
    priority: 0
- id: MGd-TUziQEKKA_xHc1tlHA
  name: ps
  description: ''
  type:
    id: jUwODgyNjAyNzk2NTk1NDY
    name: Textbox
    source: System
  locators:
  - name: TAGNAME
    value: input
    priority: 0
projectParameters: []
addons: []
